# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df9f3b81dd22e2ae1bda297d1224741129174a30c8b28fba9bf778e5029b18cac2f39e7c9c85f35aa2effb816a829f6aca59565808bd76b041ff1a448695783e

test:
  secret_key_base: 5fa2847be7b2b0f95b3f547bc06c7ad89a1894d582ab6f376051d453e63e709f7297327208d1328858f74b3dc1f179f73ee0a944f3ac3847e52f6794e6053619

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_analytics_code: YOUR CODE HERE
  host: YOUR PRODUCTION HOST URL/IP HERE
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>